name: "Upload Release Assets (Linux, Darwin, Windows)"
description: "Create a release, upload release assets, multi-platform support(Linux, Darwin, Windows)"
author: "wzshiming"

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH//\\//}/upload-release-assets.sh
      #  ${{ github.action_path }} does not work properly with Bash in Windows
      shell: bash
